name: ❗ Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["issue • bug"]
assignees:
  - andyone

body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]  
        > Before you open an issue, search GitHub Issues for a similar bug reports. If so, please add a 👍 reaction to the existing issue.

  - type: textarea
    attributes:
      label: Module version info
      description: Output of `grep 'github.com/essentialkaos/branca' go.sum` command
      render: shell
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Short guide on how to reproduce this problem on our site
      placeholder: |
        1. [First Step]
        2. [Second Step]
        3. [and so on...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Include gist of relevant config, logs, etc.
